// Airports offered in the quote form. Typing a place that is not here is fine; the team prices it either way.
// Africa came from the original homepage widget (MOPT corrected to MZI); the last block is common diaspora and hub cities.

export type Airport = { code: string; city: string; country: string; airport: string };

export const AIRPORTS: Airport[] = [
  { code: "DSS", city: "Dakar", country: "Senegal", airport: "" },
  { code: "LFW", city: "Lomé", country: "Togo", airport: "" },
  { code: "DLA", city: "Douala", country: "Cameroon", airport: "" },
  { code: "HRE", city: "Harare", country: "Zimbabwe", airport: "" },
  { code: "ADD", city: "Addis Ababa", country: "Ethiopia", airport: "" },
  { code: "NBO", city: "Nairobi", country: "Kenya", airport: "" },
  { code: "JNB", city: "Johannesburg", country: "South Africa", airport: "" },
  { code: "CPT", city: "Cape Town", country: "South Africa", airport: "" },
  { code: "CAI", city: "Cairo", country: "Egypt", airport: "" },
  { code: "CMN", city: "Casablanca", country: "Morocco", airport: "" },
  { code: "COO", city: "Cotonou", country: "Benin", airport: "Cadjehoun" },
  { code: "PKO", city: "Parakou", country: "Benin", airport: "" },
  { code: "OUA", city: "Ouagadougou", country: "Burkina Faso", airport: "" },
  { code: "BOY", city: "Bobo Dioulasso", country: "Burkina Faso", airport: "" },
  { code: "SID", city: "Sal", country: "Cabo Verde", airport: "Amílcar Cabral" },
  { code: "RAI", city: "Praia", country: "Cabo Verde", airport: "Nelson Mandela" },
  { code: "ABJ", city: "Abidjan", country: "Côte d'Ivoire", airport: "Félix Houphouët Boigny" },
  { code: "ASK", city: "Yamoussoukro", country: "Côte d'Ivoire", airport: "" },
  { code: "BYK", city: "Bouaké", country: "Côte d'Ivoire", airport: "" },
  { code: "SPY", city: "San Pédro", country: "Côte d'Ivoire", airport: "" },
  { code: "BJL", city: "Banjul", country: "Gambia", airport: "" },
  { code: "ACC", city: "Accra", country: "Ghana", airport: "Kotoka" },
  { code: "KMS", city: "Kumasi", country: "Ghana", airport: "" },
  { code: "TML", city: "Tamale", country: "Ghana", airport: "" },
  { code: "TKD", city: "Takoradi", country: "Ghana", airport: "" },
  { code: "CKY", city: "Conakry", country: "Guinea", airport: "Ahmed Sékou Touré" },
  { code: "KNN", city: "Kankan", country: "Guinea", airport: "" },
  { code: "NZE", city: "N'Zérékoré", country: "Guinea", airport: "" },
  { code: "OXB", city: "Bissau", country: "Guinea-Bissau", airport: "Osvaldo Vieira" },
  { code: "ROB", city: "Monrovia", country: "Liberia", airport: "Roberts" },
  { code: "MLW", city: "Monrovia", country: "Liberia", airport: "Spriggs Payne" },
  { code: "BKO", city: "Bamako", country: "Mali", airport: "Modibo Keita" },
  { code: "MZI", city: "Mopti", country: "Mali", airport: "" },
  { code: "TMB", city: "Timbuktu", country: "Mali", airport: "" },
  { code: "GAQ", city: "Gao", country: "Mali", airport: "" },
  { code: "NKC", city: "Nouakchott Oumtounsy", country: "Mauritania", airport: "" },
  { code: "NDB", city: "Nouadhibou", country: "Mauritania", airport: "" },
  { code: "NIM", city: "Niamey", country: "Niger", airport: "Diori Hamani" },
  { code: "AJY", city: "Agadez", country: "Niger", airport: "" },
  { code: "ZND", city: "Zinder", country: "Niger", airport: "" },
  { code: "LOS", city: "Lagos", country: "Nigeria", airport: "Murtala Muhammed" },
  { code: "ABV", city: "Abuja", country: "Nigeria", airport: "Nnamdi Azikiwe" },
  { code: "PHC", city: "Port Harcourt", country: "Nigeria", airport: "" },
  { code: "KAN", city: "Kano", country: "Nigeria", airport: "Mallam Aminu Kano" },
  { code: "ENU", city: "Enugu", country: "Nigeria", airport: "Akanu Ibiam" },
  { code: "KAD", city: "Kaduna", country: "Nigeria", airport: "" },
  { code: "ILR", city: "Ilorin", country: "Nigeria", airport: "" },
  { code: "QRW", city: "Warri", country: "Nigeria", airport: "" },
  { code: "BNI", city: "Benin City", country: "Nigeria", airport: "" },
  { code: "CBQ", city: "Calabar", country: "Nigeria", airport: "" },
  { code: "QOW", city: "Owerri", country: "Nigeria", airport: "" },
  { code: "CSK", city: "Cap Skirring", country: "Senegal", airport: "" },
  { code: "XLS", city: "Saint-Louis", country: "Senegal", airport: "" },
  { code: "FNA", city: "Freetown", country: "Sierra Leone", airport: "" },
  { code: "BJM", city: "Bujumbura", country: "Burundi", airport: "Melchior Ndadaye" },
  { code: "HAH", city: "Moroni", country: "Comoros", airport: "Prince Said Ibrahim" },
  { code: "NWA", city: "Mohéli", country: "Comoros", airport: "" },
  { code: "AJN", city: "Anjouan", country: "Comoros", airport: "" },
  { code: "JIB", city: "Djibouti Ambouli", country: "Djibouti", airport: "" },
  { code: "ASM", city: "Asmara", country: "Eritrea", airport: "" },
  { code: "MSW", city: "Massawa", country: "Eritrea", airport: "" },
  { code: "DIR", city: "Dire Dawa", country: "Ethiopia", airport: "" },
  { code: "BJR", city: "Bahir Dar", country: "Ethiopia", airport: "" },
  { code: "GDQ", city: "Gondar", country: "Ethiopia", airport: "" },
  { code: "MQX", city: "Mekelle", country: "Ethiopia", airport: "" },
  { code: "LLI", city: "Lalibela", country: "Ethiopia", airport: "" },
  { code: "WIL", city: "Nairobi", country: "Kenya", airport: "Wilson" },
  { code: "MBA", city: "Mombasa", country: "Kenya", airport: "Moi" },
  { code: "EDL", city: "Eldoret", country: "Kenya", airport: "" },
  { code: "KIS", city: "Kisumu", country: "Kenya", airport: "" },
  { code: "MYD", city: "Malindi", country: "Kenya", airport: "" },
  { code: "LAU", city: "Lamu / Manda", country: "Kenya", airport: "" },
  { code: "UKA", city: "Diani / Ukunda", country: "Kenya", airport: "" },
  { code: "TNR", city: "Antananarivo", country: "Madagascar", airport: "Ivato" },
  { code: "NOS", city: "Nosy Be", country: "Madagascar", airport: "" },
  { code: "TMM", city: "Toamasina", country: "Madagascar", airport: "" },
  { code: "TLE", city: "Toliara", country: "Madagascar", airport: "" },
  { code: "MRU", city: "Mauritius", country: "Mauritius", airport: "Sir Seewoosagur Ramgoolam" },
  { code: "RRG", city: "Rodrigues Island", country: "Mauritius", airport: "" },
  { code: "KGL", city: "Kigali", country: "Rwanda", airport: "" },
  { code: "KME", city: "Kamembe", country: "Rwanda", airport: "" },
  { code: "GYI", city: "Gisenyi", country: "Rwanda", airport: "" },
  { code: "BGD", city: "Bugesera", country: "Rwanda", airport: "" },
  { code: "SEZ", city: "Mahé", country: "Seychelles", airport: "Seychelles" },
  { code: "PRI", city: "Praslin Island", country: "Seychelles", airport: "" },
  { code: "MGQ", city: "Mogadishu", country: "Somalia", airport: "Aden Adde" },
  { code: "HGA", city: "Hargeisa Egal", country: "Somalia", airport: "" },
  { code: "JUB", city: "Juba", country: "South Sudan", airport: "" },
  { code: "MAK", city: "Malakal", country: "South Sudan", airport: "" },
  { code: "WUU", city: "Wau", country: "South Sudan", airport: "" },
  { code: "DAR", city: "Dar es Salaam", country: "Tanzania", airport: "Julius Nyerere" },
  { code: "JRO", city: "Kilimanjaro", country: "Tanzania", airport: "" },
  { code: "ZNZ", city: "Zanzibar", country: "Tanzania", airport: "Abeid Amani Karume" },
  { code: "MWZ", city: "Mwanza", country: "Tanzania", airport: "" },
  { code: "ARK", city: "Arusha", country: "Tanzania", airport: "" },
  { code: "EBB", city: "Entebbe", country: "Uganda", airport: "" },
  { code: "KJJ", city: "Kajjansi Airfield", country: "Uganda", airport: "" },
  { code: "GUL", city: "Gulu", country: "Uganda", airport: "" },
  { code: "RUA", city: "Arua", country: "Uganda", airport: "" },
  { code: "KSE", city: "Kasese", country: "Uganda", airport: "" },
  { code: "JIN", city: "Jinja Airfield", country: "Uganda", airport: "" },
  { code: "TRY", city: "Tororo Airstrip", country: "Uganda", airport: "" },
  { code: "LAD", city: "Luanda", country: "Angola", airport: "Quatro de Fevereiro" },
  { code: "SDD", city: "Lubango", country: "Angola", airport: "" },
  { code: "BUG", city: "Benguela", country: "Angola", airport: "" },
  { code: "CAB", city: "Cabinda", country: "Angola", airport: "" },
  { code: "NSI", city: "Yaoundé Nsimalen", country: "Cameroon", airport: "" },
  { code: "GRO", city: "Garoua", country: "Cameroon", airport: "" },
  { code: "BGF", city: "Bangui M'Poko", country: "CAR", airport: "" },
  { code: "NDJ", city: "N'Djamena", country: "Chad", airport: "" },
  { code: "AEH", city: "Abéché", country: "Chad", airport: "" },
  { code: "MVO", city: "Moundou", country: "Chad", airport: "" },
  { code: "FIH", city: "Kinshasa", country: "DR Congo", airport: "N'djili" },
  { code: "FBM", city: "Lubumbashi", country: "DR Congo", airport: "" },
  { code: "KWZ", city: "Kolwezi", country: "DR Congo", airport: "" },
  { code: "GOM", city: "Goma", country: "DR Congo", airport: "" },
  { code: "FKI", city: "Kisangani / Bangoka", country: "DR Congo", airport: "" },
  { code: "MJM", city: "Mbuji-Mayi", country: "DR Congo", airport: "" },
  { code: "KGA", city: "Kananga", country: "DR Congo", airport: "" },
  { code: "BKY", city: "Bukavu / Kavumu", country: "DR Congo", airport: "" },
  { code: "NLO", city: "Ndolo", country: "DR Congo", airport: "" },
  { code: "FMI", city: "Kalemie", country: "DR Congo", airport: "" },
  { code: "BUX", city: "Bunia", country: "DR Congo", airport: "" },
  { code: "SSG", city: "Malabo", country: "Equatorial Guinea", airport: "" },
  { code: "BSG", city: "Bata", country: "Equatorial Guinea", airport: "" },
  { code: "LBV", city: "Libreville Léon Mba", country: "Gabon", airport: "" },
  { code: "POG", city: "Port-Gentil", country: "Gabon", airport: "" },
  { code: "MVB", city: "Franceville", country: "Gabon", airport: "" },
  { code: "BZV", city: "Brazzaville", country: "Congo Republic", airport: "Maya-Maya" },
  { code: "PNR", city: "Pointe-Noire", country: "Congo Republic", airport: "" },
  { code: "TMS", city: "São Tomé", country: "São Tomé & Príncipe", airport: "" },
  { code: "ALG", city: "Algiers", country: "Algeria", airport: "Houari Boumediene" },
  { code: "ORN", city: "Oran", country: "Algeria", airport: "Ahmed Ben Bella" },
  { code: "CZL", city: "Constantine", country: "Algeria", airport: "" },
  { code: "AAE", city: "Annaba", country: "Algeria", airport: "" },
  { code: "HRG", city: "Hurghada", country: "Egypt", airport: "" },
  { code: "SSH", city: "Sharm El Sheikh", country: "Egypt", airport: "" },
  { code: "LXR", city: "Luxor", country: "Egypt", airport: "" },
  { code: "ASW", city: "Aswan", country: "Egypt", airport: "" },
  { code: "HBE", city: "Alexandria Borg El Arab", country: "Egypt", airport: "" },
  { code: "MJI", city: "Tripoli", country: "Libya", airport: "Mitiga" },
  { code: "BEN", city: "Benghazi", country: "Libya", airport: "Benina" },
  { code: "MRA", city: "Misrata", country: "Libya", airport: "" },
  { code: "RAK", city: "Marrakech Menara", country: "Morocco", airport: "" },
  { code: "AGA", city: "Agadir Al Massira", country: "Morocco", airport: "" },
  { code: "RBA", city: "Rabat-Salé", country: "Morocco", airport: "" },
  { code: "FEZ", city: "Fès–Saïs", country: "Morocco", airport: "" },
  { code: "TNG", city: "Tangier Ibn Batouta", country: "Morocco", airport: "" },
  { code: "PZU", city: "Port Sudan New", country: "Sudan", airport: "" },
  { code: "KRT", city: "Khartoum", country: "Sudan", airport: "" },
  { code: "TUN", city: "Tunis Carthage", country: "Tunisia", airport: "" },
  { code: "MIR", city: "Monastir Habib Bourguiba", country: "Tunisia", airport: "" },
  { code: "DJE", city: "Djerba Zarzis", country: "Tunisia", airport: "" },
  { code: "SFA", city: "Sfax", country: "Tunisia", airport: "" },
  { code: "GBE", city: "Gaborone", country: "Botswana", airport: "Sir Seretse Khama" },
  { code: "MUB", city: "Maun", country: "Botswana", airport: "" },
  { code: "BBK", city: "Kasane", country: "Botswana", airport: "" },
  { code: "SHO", city: "King Mswati III", country: "Eswatini", airport: "" },
  { code: "MSU", city: "Moshoeshoe I", country: "Lesotho", airport: "" },
  { code: "LLW", city: "Lilongwe", country: "Malawi", airport: "Kamuzu" },
  { code: "BLZ", city: "Blantyre", country: "Malawi", airport: "Chileka" },
  { code: "MPM", city: "Maputo", country: "Mozambique", airport: "" },
  { code: "BEW", city: "Beira", country: "Mozambique", airport: "" },
  { code: "APL", city: "Nampula", country: "Mozambique", airport: "" },
  { code: "POL", city: "Pemba", country: "Mozambique", airport: "" },
  { code: "WDH", city: "Windhoek", country: "Namibia", airport: "Hosea Kutako" },
  { code: "WVB", city: "Walvis Bay", country: "Namibia", airport: "" },
  { code: "ERS", city: "Windhoek", country: "Namibia", airport: "Eros" },
  { code: "DUR", city: "Durban", country: "South Africa", airport: "King Shaka" },
  { code: "HLA", city: "Johannesburg", country: "South Africa", airport: "Lanseria" },
  { code: "PLZ", city: "Port Elizabeth (Gqeberha)", country: "South Africa", airport: "" },
  { code: "GRJ", city: "George", country: "South Africa", airport: "" },
  { code: "LUN", city: "Lusaka", country: "Zambia", airport: "Kenneth Kaunda" },
  { code: "LVI", city: "Livingstone", country: "Zambia", airport: "Harry Mwaanga Nkumbula" },
  { code: "NLA", city: "Ndola", country: "Zambia", airport: "" },
  { code: "MFU", city: "Mfuwe", country: "Zambia", airport: "" },
  { code: "VFA", city: "Victoria Falls", country: "Zimbabwe", airport: "" },
  { code: "BUQ", city: "Bulawayo", country: "Zimbabwe", airport: "Joshua Mqabuko Nkomo" },
  { code: "LHR", city: "London", country: "United Kingdom", airport: "Heathrow" },
  { code: "LGW", city: "London", country: "United Kingdom", airport: "Gatwick" },
  { code: "MAN", city: "Manchester", country: "United Kingdom", airport: "" },
  { code: "CDG", city: "Paris", country: "France", airport: "Charles de Gaulle" },
  { code: "AMS", city: "Amsterdam", country: "Netherlands", airport: "Schiphol" },
  { code: "FRA", city: "Frankfurt", country: "Germany", airport: "" },
  { code: "IST", city: "Istanbul", country: "Türkiye", airport: "" },
  { code: "DXB", city: "Dubai", country: "United Arab Emirates", airport: "" },
  { code: "DOH", city: "Doha", country: "Qatar", airport: "Hamad" },
  { code: "JFK", city: "New York", country: "United States", airport: "JFK" },
  { code: "IAD", city: "Washington", country: "United States", airport: "Dulles" },
  { code: "ATL", city: "Atlanta", country: "United States", airport: "" },
  { code: "YYZ", city: "Toronto", country: "Canada", airport: "Pearson" },
  { code: "BOM", city: "Mumbai", country: "India", airport: "" },
];

/** Shown when the field is focused and empty. */
export const POPULAR = ["LOS", "ABV", "ACC", "NBO", "JNB", "ADD", "HRE", "LHR", "DXB"];
